name: CI - Frontend
on: [push]
jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: build image
        run: make docker-build  image_tag=${GITHUB_SHA}


  eks-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: phanikolluri-devops/helm-chart-v1
          path: helm
      - name: helm deploy
        run: make eks-deploy image_tag=${GITHUB_SHA}

  
        




        
